<?php

namespace App\Http\Controllers\Api;

use App\Http\Resources\Api\CommissionResource;
use App\Models\Commission;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use OpenApi\Attributes as OA;

/**
 * Mirrors App\Filament\Partner\Resources\CommissionResource - entirely
 * read-only (canCreate() is false there too; commissions are only ever
 * generated by Commission::generateForCustomer() and progressed by admin
 * actions), scoped to the authenticated partner.
 */
class CommissionController extends Controller
{
    #[OA\Get(
        path: '/commissions',
        tags: ['Commissions'],
        summary: 'Daftar komisi milik partner yang login',
        security: [['bearerAuth' => []]],
        parameters: [
            new OA\Parameter(name: 'status', in: 'query', schema: new OA\Schema(type: 'string')),
            new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer')),
        ],
        responses: [new OA\Response(response: 200, description: 'OK')]
    )]
    public function index(Request $request): JsonResponse
    {
        $commissions = Commission::query()
            ->where('partner_id', $request->user()->id)
            ->with(['customer.service'])
            ->when($request->string('status')->isNotEmpty(), fn ($q) => $q->where('status', $request->string('status')))
            ->latest()
            ->paginate($request->integer('per_page', 15));

        return CommissionResource::collection($commissions)->response();
    }

    #[OA\Get(
        path: '/commissions/{commission}',
        tags: ['Commissions'],
        summary: 'Detail komisi',
        security: [['bearerAuth' => []]],
        parameters: [new OA\Parameter(name: 'commission', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))],
        responses: [new OA\Response(response: 200, description: 'OK'), new OA\Response(response: 404, description: 'Tidak ditemukan')]
    )]
    public function show(Request $request, int $commission): CommissionResource
    {
        $record = Commission::where('partner_id', $request->user()->id)
            ->with(['customer.service'])
            ->findOrFail($commission);

        return new CommissionResource($record);
    }
}
